# Generated by Django 5.1.15 on 2026-06-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('racimos_cortados', models.PositiveIntegerField()),
                ('rejas_producidas', models.PositiveIntegerField()),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cosecha',
                'verbose_name_plural': 'cosechas',
                'ordering': ['-fecha'],
            },
        ),
    ]
