# Generated by Django 5.1.15 on 2026-06-08 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'tipo de insumo',
                'verbose_name_plural': 'tipos de insumo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CompraInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidad', models.CharField(blank=True, max_length=20)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_insumo', to=settings.AUTH_USER_MODEL)),
                ('tipo_insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='insumos.tipoinsumo')),
            ],
            options={
                'verbose_name': 'compra de insumo',
                'verbose_name_plural': 'compras de insumo',
                'ordering': ['-fecha'],
            },
        ),
    ]
