# Generated by Django 5.1.15 on 2026-06-08 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='monto_pagado',
        ),
    ]
