# Generated by Django 5.1.15 on 2026-06-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('area_hectareas', models.DecimalField(decimal_places=2, max_digits=8)),
                ('activa', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'parcela',
                'verbose_name_plural': 'parcelas',
                'ordering': ['nombre'],
            },
        ),
    ]
